document.writeln("    <main>");
document.writeln("        <div class=\'container-fluid\'>");
document.writeln("            <div class=\'row\'>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/ppw1.jpg\' alt=\'\'>");
document.writeln("                        <div class=\'bd\'>");
document.writeln("                            <div class=\'txt\'>");
document.writeln("                                <h2>嘿！道奇</h2>");
document.writeln("                                <span>—view—</span>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/ppw2.jpg\' alt=\'\'>");
document.writeln("                        <div class=\'bd\'>");
document.writeln("                            <div class=\'txt\'>");
document.writeln("                                <h2>姆明</h2>");
document.writeln("                                <span>—view—</span>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/ppw3.jpg\' alt=\'\'>");
document.writeln("                    </a>");
document.writeln("                    <div class=\'bd\'>");
document.writeln("                        <div class=\'txt\'>");
document.writeln("                            <h2>奇先生妙小姐</h2>");
document.writeln("                            <span>—view—</span>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'preAnimation/baby.html\'>");
document.writeln("                        <img src=\'../images/ppw4.png\' alt=\'嘿！double\'>");
document.writeln("                        <div class=\'bd\'>");
document.writeln("                            <div class=\'txt\'>");
document.writeln("                                <h2>天线宝宝</h2>");
document.writeln("                                <span>—view—</span>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/ppw5.jpg\' alt=\'\'>");
document.writeln("                        <div class=\'bd\'>");
document.writeln("                            <div class=\'txt\'>");
document.writeln("                                <h2>贝尔·格里尔斯</h2>");
document.writeln("                                <span>—view—</span>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/ppw6.jpg\' alt=\'嘿！double\'>");
document.writeln("                        <div class=\'bd\'>");
document.writeln("                            <div class=\'txt\'>");
document.writeln("                                <h2>探索频道</h2>");
document.writeln("                                <span>—view—</span>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'preAnimation/baby.html\'>");
document.writeln("                        <img src=\'../images/ppw7.jpg\' alt=\'\'>");
document.writeln("                        <div class=\'bd\'>");
document.writeln("                            <div class=\'txt\'>");
document.writeln("                                <h2>彩通</h2>");
document.writeln("                                <span>—view—</span>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/ppw8.jpg\' alt=\'\'>");
document.writeln("                    </a>");
document.writeln("                    <div class=\'bd\'>");
document.writeln("                        <div class=\'txt\'>");
document.writeln("                            <h2>皇家马德里足球俱乐部</h2>");
document.writeln("                            <span>—view—</span>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/ppw9.jpg\' alt=\'嘿！double\'>");
document.writeln("                        <div class=\'bd\'>");
document.writeln("                            <div class=\'txt\'>");
document.writeln("                                <h2>巴塞罗那足球俱乐部</h2>");
document.writeln("                                <span>—view—</span>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/ppw10.jpg\' alt=\'\'>");
document.writeln("                        <div class=\'bd\'>");
document.writeln("                            <div class=\'txt\'>");
document.writeln("                                <h2>马德里竞技足球俱乐部</h2>");
document.writeln("                                <span>—view—</span>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/ppw11.png\' alt=\'\'>");
document.writeln("                    </a>");
document.writeln("                    <div class=\'bd\'>");
document.writeln("                        <div class=\'txt\'>");
document.writeln("                            <h2>曼城足球俱乐部</h2>");
document.writeln("                            <span>—view—</span>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/ppw12.jpg\' alt=\'嘿！double\'>");
document.writeln("                        <div class=\'bd\'>");
document.writeln("                            <div class=\'txt\'>");
document.writeln("                                <h2>阿森纳足球俱乐部</h2>");
document.writeln("                                <span>—view—</span>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/ppw13.png\' alt=\'\'>");
document.writeln("                        <div class=\'bd\'>");
document.writeln("                            <div class=\'txt\'>");
document.writeln("                                <h2>法国国家足球队</h2>");
document.writeln("                                <span>—view—</span>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/ppw14.jpg\' alt=\'\'>");
document.writeln("                        <div class=\'bd\'>");
document.writeln("                            <div class=\'txt\'>");
document.writeln("                                <h2>荷兰皇家足球协会</h2>");
document.writeln("                                <span>—view—</span>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/ppw15.png\' alt=\'\'>");
document.writeln("                        <div class=\'bd\'>");
document.writeln("                            <div class=\'txt\'>");
document.writeln("                                <h2>荷兰皇家足球协会</h2>");
document.writeln("                                <span>—view—</span>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </main>");
document.writeln("");
document.writeln("    <footer>");
document.writeln("        <div class=\'fobd\'>");
document.writeln("            <p>琼ICP备000000000号 联系电话：00000000000 联系地址：xxxxxxxxxxx 联系邮箱：xxxxxxxxxxxx 版权所有：深圳山成丰盈企业管理咨询有限公司</p>");
document.writeln("        </div>");
document.writeln("    </footer>");
