document.writeln("    <div class=\'switch\'>");
document.writeln("        <a href=\'\'><span>CN</span></a>");
document.writeln("    </div>");
document.writeln("    <div class=\'nav\'>");
document.writeln("        <div class=\'one\'>");
document.writeln("            <a href=\'#\' id=\'first\'><img src=\'../images/me.png\' alt=\'\'></a>");
document.writeln("            <div class=\'more\'>");
document.writeln("                <ul id=\'second\'>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'../index.html\'>首页</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a id=\'preS\' href=\'#\'>学前动画</a>");
document.writeln("                    </li>");
document.writeln("                    <div id=\'pre\'>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'hiDo.html\'>嘿！道奇</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'moomMi.html\'>姆明</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'mr.html\'>奇先生妙小姐</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'baby.html\'>天线宝宝</a>");
document.writeln("                        </li>");
document.writeln("                    </div>");
document.writeln("                    <li id=\'lifeS\'>");
document.writeln("                        <a href=\'#\'>生活方式</a>");
document.writeln("                    </li>");
document.writeln("                    <div id=\'life\'>");
document.writeln("                        <li><a href=\'bear.html\'>贝尔·格里尔斯</a></li>");
document.writeln("                        <li><a href=\'discover.html\'>探索频道</a></li>");
document.writeln("                        <li><a href=\'pantone.html\'>彩通</a></li>");
document.writeln("                    </div>");
document.writeln("                    <li id=\'sportS\'>");
document.writeln("                        <a href=\'#\'>运动</a>");
document.writeln("                    </li>");
document.writeln("                    <div id=\'sport\'>");
document.writeln("                        <li><a href=\'hJia.html\'>皇家马德里足球俱乐部</a></li>");
document.writeln("                        <li><a href=\'baShai.html\'>巴塞罗那足球俱乐部</a></li>");
document.writeln("                        <li><a href=\'maDe.html\'>马德里竞技足球俱乐部</a></li>");
document.writeln("                        <li><a href=\'manC.html\'>曼城足球俱乐部</a></li>");
document.writeln("                        <li><a href=\'aSheng.html\'>阿森纳足球俱乐部</a></li>");
document.writeln("                        <li><a href=\'french.html\'>法国国家足球队</a></li>");
document.writeln("                        <li><a href=\'heLan.html\'>荷兰皇家足球协会</a></li>");
document.writeln("                    </div>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'aboutUs.html\'>关于我们</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'two\'>");
document.writeln("            <a href=\'../index.html\'><img src=\'../images/logo.png\' alt=\'\'></a>");
document.writeln("        </div>");
document.writeln("        <div class=\'three\'>");
document.writeln("            <a href=\'\'>EN</a>");
document.writeln("            <span>/</span>");
document.writeln("            <a href=\'\'>CN</a>");
document.writeln("        </div>");
document.writeln("        <div class=\'menu\'>");
document.writeln("            <ul>");
document.writeln("                <li><a href=\'../index.html\'>首页</a></li>");
document.writeln("                <li><a href=\'\'>学前动画</a>");
document.writeln("                    <ul>");
document.writeln("                        <li><a href=\'hiDo.html\'>嘿！道奇</a></li>");
document.writeln("                        <li><a href=\'moomMi.html\'>姆明</a></li>");
document.writeln("                        <li><a href=\'mr.html\'>奇先生妙小姐</a></li>");
document.writeln("                        <li><a href=\'baby.html\'>天线宝宝</a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li><a href=\'\'>生活方式</a>");
document.writeln("                    <ul>");
document.writeln("                        <li><a href=\'bear.html\'>贝尔·格里尔斯</a></li>");
document.writeln("                        <li><a href=\'discover.html\'>探索频道</a></li>");
document.writeln("                        <li><a href=\'pantone.html\'>彩通</a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li><a href=\'\'>运动</a>");
document.writeln("                    <ul>");
document.writeln("                        <li><a href=\'hJia.html\'>皇家马德里足球俱乐部</a></li>");
document.writeln("                        <li><a href=\'baShai.html\'>巴塞罗那足球俱乐部</a></li>");
document.writeln("                        <li><a href=\'maDe.html\'>马德里竞技足球俱乐部</a></li>");
document.writeln("                        <li><a href=\'manC.html\'>曼城足球俱乐部</a></li>");
document.writeln("                        <li><a href=\'aSheng.html\'>阿森纳足球俱乐部</a></li>");
document.writeln("                        <li><a href=\'french.html\'>法国国家足球队</a></li>");
document.writeln("                        <li><a href=\'heLan.html\'>荷兰皇家足球协会</a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li><a href=\'\'>案例</a></li>");
document.writeln("                <li><a href=\'\'>荣誉</a></li>");
document.writeln("                <li><a href=\'aboutUs.html\'>关于我们</a></li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");