document.writeln("<!DOCTYPE html>");
document.writeln("");
document.writeln("<head lang=\'zh-CN\'>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1, shrink-to-fit=no\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'ie=edge\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'../css/bootstrap.min.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'../css/main.css\'>");
document.writeln("    <title>ppw</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("    <main>");
document.writeln("        <div class=\'container-fluid\'>");
document.writeln("            <div class=\'row\'>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/PPW2_21.png\' alt=\'嘿！double\'>");
document.writeln("                    </a>");
document.writeln("                    <div class=\'bd\'>");
document.writeln("                        <div class=\'txt\'>");
document.writeln("                            <h2>嘿！This is the test 1</h2>");
document.writeln("                            <span>—000—</span>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/PPW2_22.png\' alt=\'\'>");
document.writeln("                        <div class=\'bd\'>");
document.writeln("                            <div class=\'txt\'>");
document.writeln("                                <h2>嘿！This is the test 2</h2>");
document.writeln("                                <span>—000—</span>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/PPW2_23.png\' alt=\'\'>");
document.writeln("                    </a>");
document.writeln("                    <div class=\'bd\'>");
document.writeln("                        <div class=\'txt\'>");
document.writeln("                            <h2>嘿！This is the test 3</h2>");
document.writeln("                            <span>—000—</span>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/PPW2_24.png\' alt=\'\'>");
document.writeln("                    </a>");
document.writeln("                    <div class=\'bd\'>");
document.writeln("                        <div class=\'txt\'>");
document.writeln("                            <h2>嘿！This is the test 4</h2>");
document.writeln("                            <span>—000—</span>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/PPW2_25.png\' alt=\'\'>");
document.writeln("                    </a>");
document.writeln("                    <div class=\'bd\'>");
document.writeln("                        <div class=\'txt\'>");
document.writeln("                            <h2>嘿！This is the test 5</h2>");
document.writeln("                            <span>—000—</span>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/PPW2_26.png\' alt=\'\'>");
document.writeln("                    </a>");
document.writeln("                    <div class=\'bd\'>");
document.writeln("                        <div class=\'txt\'>");
document.writeln("                            <h2>嘿！This is the test 6</h2>");
document.writeln("                            <span>—000—</span>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/PPW2_27.png\' alt=\'\'>");
document.writeln("                    </a>");
document.writeln("                    <div class=\'bd\'>");
document.writeln("                        <div class=\'txt\'>");
document.writeln("                            <h2>嘿！This is the test 7</h2>");
document.writeln("                            <span>—000—</span>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/PPW2_28.png\' alt=\'\'>");
document.writeln("                    </a>");
document.writeln("                    <div class=\'bd\'>");
document.writeln("                        <div class=\'txt\'>");
document.writeln("                            <h2>嘿！This is the test 8</h2>");
document.writeln("                            <span>—000—</span>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/PPW2_11.png\' alt=\'\'>");
document.writeln("                    </a>");
document.writeln("                    <div class=\'bd\'>");
document.writeln("                        <div class=\'txt\'>");
document.writeln("                            <h2>嘿！This is the test 9</h2>");
document.writeln("                            <span>—000—</span>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/PPW2_12.png\' alt=\'\'>");
document.writeln("                    </a>");
document.writeln("                    <div class=\'bd\'>");
document.writeln("                        <div class=\'txt\'>");
document.writeln("                            <h2>嘿！This is the test 10</h2>");
document.writeln("                            <span>—000—</span>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/PPW2_13.png\' alt=\'\'>");
document.writeln("                    </a>");
document.writeln("                    <div class=\'bd\'>");
document.writeln("                        <div class=\'txt\'>");
document.writeln("                            <h2>嘿！This is the test 11</h2>");
document.writeln("                            <span>—000—</span>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/PPW2_14.png\' alt=\'\'>");
document.writeln("                    </a>");
document.writeln("                    <div class=\'bd\'>");
document.writeln("                        <div class=\'txt\'>");
document.writeln("                            <h2>嘿！This is the test 12</h2>");
document.writeln("                            <span>—000—</span>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/PPW2_15.png\' alt=\'\'>");
document.writeln("                    </a>");
document.writeln("                    <div class=\'bd\'>");
document.writeln("                        <div class=\'txt\'>");
document.writeln("                            <h2>嘿！This is the test 13</h2>");
document.writeln("                            <span>—000—</span>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/PPW2_27.png\' alt=\'\'>");
document.writeln("                    </a>");
document.writeln("                    <div class=\'bd\'>");
document.writeln("                        <div class=\'txt\'>");
document.writeln("                            <h2>嘿！This is the test 14</h2>");
document.writeln("                            <span>—000—</span>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/PPW2_17.png\' alt=\'\'>");
document.writeln("                    </a>");
document.writeln("                    <div class=\'bd\'>");
document.writeln("                        <div class=\'txt\'>");
document.writeln("                            <h2>PANTONE</h2>");
document.writeln("                            <span>—view—</span>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/PPW2_18.png\' alt=\'\'>");
document.writeln("                    </a>");
document.writeln("                    <div class=\'bd\'>");
document.writeln("                        <div class=\'txt\'>");
document.writeln("                            <h2>嘿！This is the test 16</h2>");
document.writeln("                            <span>—000—</span>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/PPW2_19.png\' alt=\'\'>");
document.writeln("                    </a>");
document.writeln("                    <div class=\'bd\'>");
document.writeln("                        <div class=\'txt\'>");
document.writeln("                            <h2>嘿！This is the test 17</h2>");
document.writeln("                            <span>—000—</span>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mbig\'>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'../images/PPW2_20.png\' alt=\'\'>");
document.writeln("                    </a>");
document.writeln("                    <div class=\'bd\'>");
document.writeln("                        <div class=\'txt\'>");
document.writeln("                            <h2>嘿！This is the test 18</h2>");
document.writeln("                            <span>—000—</span>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </main>");
document.writeln("    <footer>");
document.writeln("        <div class=\'fobd\'>");
document.writeln("            <p>琼ICP备000000000号 联系电话：00000000000 联系地址：xxxxxxxxxxx 联系邮箱：xxxxxxxxxxxx 版权所有：深圳山成丰盈企业管理咨询有限公司</p>");
document.writeln("        </div>");
document.writeln("    </footer>");
document.writeln("");
document.writeln("");
document.writeln("    <script src=\'https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js\'></script>");
document.writeln("    <script src=\'js/bootstrap.bundle.min.js\'></script>");
document.writeln("    <script text=\'javascript\' src=\'js/bootstrap.min.js\'></script>");
document.writeln("    <script text=\'javascript\' src=\'js/main.js\'></script>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");